# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uPort-demo-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    
  target 'uPort-demo-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uPort-demo-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
